[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_program = "8rmAWK5EZQHgYJL4DRa1HtqZcQMiDaoZVTCYdcoV9xut"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/efe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
